baseURL = 'https://pure-shape.pl/'
defaultContentLanguage = 'pl'
title = 'Pure Shape Studio'
disableKinds = ['taxonomy', 'term']

[languages.pl]
  languageCode = 'pl-PL'
  languageName = 'PL'
  weight = 1

[languages.en]
  languageCode = 'en-GB'
  languageName = 'EN'
  weight = 2
